#############################################################################
port: 7054
debug: false
crlsizelimit: 512000
#############################################################################
tls:
  enabled: false
  certfile: ca-cert.pem
  keyfile: ca-key.pem
  clientauth:
    type: noclientcert
    certfiles:
#############################################################################
ca:
  name:
  keyfile: ca-key.pem
  certfile: ca-cert.pem
  chainfile: ca-chain.pem
#############################################################################
registry:
  maxenrollments: -1
  identities:
    - name: admin
      pass: adminpw
      type: client
      affiliation: ""
      attrs:
        hf.Registrar.Roles: "client,user,peer,validator,auditor"
        hf.Registrar.DelegateRoles: "client,user,validator,auditor"
        hf.Revoker: true
        hf.IntermediateCA: true
#############################################################################
db:
  type: sqlite3
  datasource: fabric-ca-server.db
  tls:
    enabled: false
    certfiles:
      - db-server-cert.pem
    client:
      certfile: db-client-cert.pem
      keyfile: db-client-key.pem
#############################################################################
ldap:
  enabled: false
  url: ldap://<adminDN>:<adminPassword>@<host>:<port>/<base>
  tls:
    certfiles:
      - ldap-server-cert.pem
    client:
      certfile: ldap-client-cert.pem
      keyfile: ldap-client-key.pem
#############################################################################
affiliations:
  org1:
    - department1
  org2:
    - department1
  org3:
    - department1
  org4:
    - department1
  org5:
    - department1
  org6:
    - department1
  org7:
    - department1
  org8:
    - department1
  org9:
    - department1
  org10:
    - department1
  org11:
    - department1
  org12:
    - department1
  org13:
    - department1
  org14:
    - department1
  org15:
    - department1
  org16:
    - department1
  org17:
    - department1
  org18:
    - department1
  org19:
    - department1
  org20:
    - department1
  org21:
    - department1
  org22:
    - department1
  org23:
    - department1
  org24:
    - department1
  org25:
    - department1
  org26:
    - department1
  org27:
    - department1
  org28:
    - department1
  org29:
    - department1
  org30:
    - department1
  org31:
    - department1
  org32:
    - department1
  org33:
    - department1
  org34:
    - department1
  org35:
    - department1
  org36:
    - department1
  org37:
    - department1
  org38:
    - department1
  org39:
    - department1
  org40:
    - department1
  org41:
    - department1
  org42:
    - department1
  org43:
    - department1
  org44:
    - department1
  org45:
    - department1
  org46:
    - department1
  org47:
    - department1
  org48:
    - department1
  org49:
    - department1
  org50:
    - department1
  org51:
    - department1
  org52:
    - department1
  org53:
    - department1
  org54:
    - department1
  org55:
    - department1
  org56:
    - department1
  org57:
    - department1
  org58:
    - department1
  org59:
    - department1
  org60:
    - department1
  org61:
    - department1
  org62:
    - department1
  org63:
    - department1
  org64:
    - department1
  org65:
    - department1
  org66:
    - department1
  org67:
    - department1
  org68:
    - department1
  org69:
    - department1
  org70:
    - department1
  org71:
    - department1
  org72:
    - department1
  org73:
    - department1
  org74:
    - department1
  org75:
    - department1
  org76:
    - department1
  org77:
    - department1
  org78:
    - department1
  org79:
    - department1
  org80:
    - department1
  org81:
    - department1
  org82:
    - department1
  org83:
    - department1
  org84:
    - department1
  org85:
    - department1
  org86:
    - department1
  org87:
    - department1
  org88:
    - department1
  org89:
    - department1
  org90:
    - department1
  org91:
    - department1
  org92:
    - department1
  org93:
    - department1
  org94:
    - department1
  org95:
    - department1
  org96:
    - department1
  org97:
    - department1
  org98:
    - department1
  org99:
    - department1
  org100:
    - department1
  org101:
    - department1
  org102:
    - department1
  org103:
    - department1
  org104:
    - department1
  org105:
    - department1
  org106:
    - department1
  org107:
    - department1
  org108:
    - department1
  org109:
    - department1
  org110:
    - department1
  org111:
    - department1
  org112:
    - department1
  org113:
    - department1
  org114:
    - department1
  org115:
    - department1
  org116:
    - department1
  org117:
    - department1
  org118:
    - department1
  org119:
    - department1
  org120:
    - department1
  org121:
    - department1
  org122:
    - department1
  org123:
    - department1
  org124:
    - department1
  org125:
    - department1
  org126:
    - department1
  org127:
    - department1
  org128:
    - department1
  org129:
    - department1
  org130:
    - department1
  org131:
    - department1
  org132:
    - department1
  org133:
    - department1
  org134:
    - department1
  org135:
    - department1
  org136:
    - department1
  org137:
    - department1
  org138:
    - department1
  org139:
    - department1
  org140:
    - department1
  org141:
    - department1
  org142:
    - department1
  org143:
    - department1
  org144:
    - department1
  org145:
    - department1
  org146:
    - department1
  org147:
    - department1
  org148:
    - department1
  org149:
    - department1
  org150:
    - department1
  org151:
    - department1
  org152:
    - department1
  org153:
    - department1
  org154:
    - department1
  org155:
    - department1
  org156:
    - department1
  org157:
    - department1
  org158:
    - department1
  org159:
    - department1
  org160:
    - department1
  org161:
    - department1
  org162:
    - department1
  org163:
    - department1
  org164:
    - department1
  org165:
    - department1
  org166:
    - department1
  org167:
    - department1
  org168:
    - department1
  org169:
    - department1
  org170:
    - department1
  org171:
    - department1
  org172:
    - department1
  org173:
    - department1
  org174:
    - department1
  org175:
    - department1
  org176:
    - department1
  org177:
    - department1
  org178:
    - department1
  org179:
    - department1
  org180:
    - department1
  org181:
    - department1
  org182:
    - department1
  org183:
    - department1
  org184:
    - department1
  org185:
    - department1
  org186:
    - department1
  org187:
    - department1
  org188:
    - department1
  org189:
    - department1
  org190:
    - department1
  org191:
    - department1
  org192:
    - department1
  org193:
    - department1
  org194:
    - department1
  org195:
    - department1
  org196:
    - department1
  org197:
    - department1
  org198:
    - department1
  org199:
    - department1
  org200:
    - department1
#############################################################################
signing:
  default:
    usage:
      - digital signature
    expiry: 8760h
  profiles:
    ca:
      usage:
        - cert sign
      expiry: 43800h
      caconstraint:
        isca: true
        maxpathlen: 0
#############################################################################
csr:
  cn: fabric-ca-server
  names:
    - C: US
      ST: "North Carolina"
      L:
      O: Hyperledger
      OU: Fabric
  hosts:
    - ca2bab1d1c73
    - localhost
  ca:
    expiry: 131400h
    pathlength: 1
#############################################################################
bccsp:
  default: SW
  sw:
    hash: SHA2
    security: 256
    filekeystore:
      keystore: msp/keystore
#############################################################################
cacount:
cafiles:
#############################################################################
intermediate:
  parentserver:
    url:
    caname:
  enrollment:
    hosts:
    profile:
    label:
  tls:
    certfiles:
    client:
      certfile:
      keyfile:
